BEGIN;

ALTER TABLE deletion_tombstones
    ADD COLUMN cursor_sequence bigint GENERATED BY DEFAULT AS IDENTITY;

WITH ordered_tombstones AS (
    SELECT tenant_id,
           tombstone_id,
           row_number() OVER (ORDER BY requested_at, tombstone_id, tenant_id) AS cursor_sequence
    FROM deletion_tombstones
)
UPDATE deletion_tombstones AS tombstone
SET cursor_sequence = ordered.cursor_sequence
FROM ordered_tombstones AS ordered
WHERE tombstone.tenant_id = ordered.tenant_id
  AND tombstone.tombstone_id = ordered.tombstone_id;

CREATE UNIQUE INDEX deletion_tombstones_cursor_sequence_idx
    ON deletion_tombstones (tenant_id, cursor_sequence);

INSERT INTO schema_migrations (version) VALUES (13);

COMMIT;
