"""Stable domain vocabulary for MindBridge memory."""

from mindbridge.core.errors import (
    DomainInvariantError,
    EnumerationLimitExceededError,
    ForgetTargetNotFoundError,
    IdempotencyConflictError,
    JobNotFoundError,
    MemoryDeletedError,
    MemoryIntegrityError,
    MemoryNotFoundError,
    ModelOutputError,
    ModelUnavailableError,
    ObjectStorageError,
    TaskBrokerError,
)
from mindbridge.core.evidence import (
    EvidenceSpan,
    MediaKind,
    MediaObject,
    Observation,
    PixelRegion,
    SensorKind,
)
from mindbridge.core.feedback import FeedbackType, MemoryFeedback
from mindbridge.core.forget import (
    DeletionPropagationState,
    DeletionTombstone,
    ForgetTargetType,
)
from mindbridge.core.identifiers import (
    ClaimId,
    DeviceId,
    EmbeddingId,
    EventId,
    EvidenceId,
    FeedbackId,
    JobId,
    MediaObjectId,
    MemoryId,
    ObservationId,
    TenantId,
    TombstoneId,
    derive_observation_id,
    derive_stable_id,
)
from mindbridge.core.identity import AnonymousIdentityObservation, IdentityKind, IdentityMention
from mindbridge.core.jobs import JobState, ObservationJobClaim, ObservationProcessingJob
from mindbridge.core.lifecycle import (
    DEFAULT_MEMORY_STRENGTH_POLICY,
    MemoryStrengthPolicy,
    apply_memory_feedback,
    calculate_memory_strength,
    evolve_memory_strength,
)
from mindbridge.core.memory import (
    Claim,
    EmbeddedObjectType,
    EmbeddingRecord,
    EmbeddingSpaceReference,
    Event,
    MemoryRecord,
    MemoryState,
    MemoryType,
    ModelReference,
    VerificationStatus,
)

__all__ = [
    "DEFAULT_MEMORY_STRENGTH_POLICY",
    "AnonymousIdentityObservation",
    "Claim",
    "ClaimId",
    "DeletionPropagationState",
    "DeletionTombstone",
    "DeviceId",
    "DomainInvariantError",
    "EmbeddedObjectType",
    "EmbeddingId",
    "EmbeddingRecord",
    "EmbeddingSpaceReference",
    "EnumerationLimitExceededError",
    "Event",
    "EventId",
    "EvidenceId",
    "EvidenceSpan",
    "FeedbackId",
    "FeedbackType",
    "ForgetTargetNotFoundError",
    "ForgetTargetType",
    "IdempotencyConflictError",
    "IdentityKind",
    "IdentityMention",
    "JobId",
    "JobNotFoundError",
    "JobState",
    "MediaKind",
    "MediaObject",
    "MediaObjectId",
    "MemoryDeletedError",
    "MemoryFeedback",
    "MemoryId",
    "MemoryIntegrityError",
    "MemoryNotFoundError",
    "MemoryRecord",
    "MemoryState",
    "MemoryStrengthPolicy",
    "MemoryType",
    "ModelOutputError",
    "ModelReference",
    "ModelUnavailableError",
    "ObjectStorageError",
    "Observation",
    "ObservationId",
    "ObservationJobClaim",
    "ObservationProcessingJob",
    "PixelRegion",
    "SensorKind",
    "TaskBrokerError",
    "TenantId",
    "TombstoneId",
    "VerificationStatus",
    "apply_memory_feedback",
    "calculate_memory_strength",
    "derive_observation_id",
    "derive_stable_id",
    "evolve_memory_strength",
]
