"""Embodied memory as a service.

The client and every contract it exchanges are importable from here, so the first call costs
one import rather than two. `mindbridge.contracts` remains the module that defines them.
"""

from mindbridge.contracts import (
    DeletionListRequest,
    DeletionPage,
    DeletionTombstoneView,
    ErrorResponse,
    EvidenceView,
    FeedbackReceipt,
    FeedbackRequest,
    ForgetReceipt,
    ForgetRequest,
    GetMemoryRequest,
    GetObservationJobRequest,
    HealthResponse,
    IdentityObservationInput,
    MediaObjectInput,
    MemoryResult,
    MemoryView,
    MemoryWriteStatus,
    ObservationProcessingJobView,
    ObservationReceipt,
    ObservationStatus,
    ObserveRequest,
    RecallFilters,
    RecallMode,
    RecallQuery,
    RecallRequest,
    RecallResult,
    RememberRequest,
    RememberResult,
    ValidationIssue,
)
from mindbridge.core import (
    DeletionPropagationState,
    FeedbackType,
    ForgetTargetType,
    IdentityKind,
    IdentityScope,
    JobState,
    MediaKind,
    MemoryState,
    MemoryType,
    SensorKind,
    VerificationStatus,
)
from mindbridge.sdk import MindBridge, MindBridgeError, ObservationJobEvent

__all__ = [
    "DeletionListRequest",
    "DeletionPage",
    "DeletionPropagationState",
    "DeletionTombstoneView",
    "ErrorResponse",
    "EvidenceView",
    "FeedbackReceipt",
    "FeedbackRequest",
    "FeedbackType",
    "ForgetReceipt",
    "ForgetRequest",
    "ForgetTargetType",
    "GetMemoryRequest",
    "GetObservationJobRequest",
    "HealthResponse",
    "IdentityKind",
    "IdentityObservationInput",
    "IdentityScope",
    "JobState",
    "MediaKind",
    "MediaObjectInput",
    "MemoryResult",
    "MemoryState",
    "MemoryType",
    "MemoryView",
    "MemoryWriteStatus",
    "MindBridge",
    "MindBridgeError",
    "ObservationJobEvent",
    "ObservationProcessingJobView",
    "ObservationReceipt",
    "ObservationStatus",
    "ObserveRequest",
    "RecallFilters",
    "RecallMode",
    "RecallQuery",
    "RecallRequest",
    "RecallResult",
    "RememberRequest",
    "RememberResult",
    "SensorKind",
    "ValidationIssue",
    "VerificationStatus",
]
